"""Initial migration

Revision ID: 10910fbe1add
Revises: 
Create Date: 2026-06-11 13:26:41.586602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10910fbe1add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drug_a', sa.String(length=100), nullable=False),
    sa.Column('drug_b', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_a', 'drug_b', name='unique_drug_pair')
    )
    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drug_interactions_drug_a'), ['drug_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_interactions_drug_b'), ['drug_b'], unique=False)

    op.create_table('queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=True),
    sa.Column('has_interaction_warnings', sa.Boolean(), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drug_interactions_drug_b'))
        batch_op.drop_index(batch_op.f('ix_drug_interactions_drug_a'))

    op.drop_table('drug_interactions')
    op.drop_table('documents')
    # ### end Alembic commands ###
